version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.0
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@types/react-router"
    versions:
    - 5.1.12
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.2
  - dependency-name: react-scripts
    versions:
    - 4.0.2
